

services:

  backend:
    env_file:
      - ./backend/.env
    build: ./backend
    container_name: notify-backend
    ports:
      - "5000:5000"
    

    
  frontend:
    build: ./frontend
    container_name: notify-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

