name: Deploy to EC2

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add EC2 Host to Known Hosts
        run: ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2 using SSH
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no $USER@$HOST << 'ENDSSH'
            set -e
            cd ~/notify
            echo "Pulling latest code..."
            git pull origin main
            echo "Stopping containers..."
            docker compose down || true
            echo "Building and starting containers..."
            docker compose up -d --build
            echo "Cleaning up old images..."
            docker image prune -f
            echo "Deployment complete!"
            docker compose ps
          ENDSSH